### ISSUE TITLE
Installing via setup.py introduces openssl error

### ISSUE THREAD

**Issue by jeunito** [akamai-open/api-kickstart#49] opened 2016-07-16 00:00 UTC
There is something wrong with how setup.py is configured. I followed the instructions in the documentation but get an error when running ```python diagnostic_tools.py```:

```
(akamai) $ python --version
Python 2.7.12
(akamai) $ python -c 'import ssl;print ssl.OPENSSL_VERSION'
OpenSSL 1.0.2h  3 May 2016
(akamai) $ cd api-kickstart/examples/python/tools
(akamai) $ python setup.py install
...
(akamai) $ python diagnostic_tools.py
...
RuntimeError: You are linking against OpenSSL 0.9.8, which is no longer support by the OpenSSL project. You need to upgrade to a newer version of OpenSSL.
```

However, when I install the dependencies one by one, I do not get the error above: 

```
(akam) $ python --version
Python 2.7.12
(akam) $ python -c 'import ssl;print ssl.OPENSSL_VERSION'
OpenSSL 1.0.2h  3 May 2016
(akam) $ pip install requests
(akam) $ pip install edgegrid-python
(akam) $ python diagnostic_tools.py
...
...
Requesting locations that support the diagnostic-tools API.

There are xx locations that can run dig in the Akamai Network
We will make our call from xx, xx
...
```

Both examples above were made using different virtualenvs

**Comment by synedra** [comment] 2016-08-25 18:22
This is probably more helpful:
https://github.com/pyca/cryptography/issues/3043

**Comment by synedra** [comment] 2016-09-16 08:29
Closing as I can't reproduce - if you get more info please let me know!

**Closed by synedra** 2016-09-16 08:29 UTC
