### ISSUE TITLE
Run diagnostic_tools.py error

### ISSUE THREAD

**Issue by tylerwei** [akamai-open/api-kickstart#11] opened 2015-06-16 09:28 UTC
when I running diagnostic_tools.py report error， error msg is:

Traceback (most recent call last):
  File "diagnostic_tools.py", line 19, in <module>
    import requests, logging, json, sys
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/contrib/pyopenssl.py", line 48, in <module>
    from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
  File "/usr/local/lib/python2.7/dist-packages/ndg_httpsclient-0.4.0-py2.7.egg/ndg/httpsclient/ssl_peer_verification.py", line 14, in <module>
    from ndg.httpsclient.subj_alt_name import SubjectAltName
  File "/usr/local/lib/python2.7/dist-packages/ndg_httpsclient-0.4.0-py2.7.egg/ndg/httpsclient/subj_alt_name.py", line 102, in <module>
    class AnotherName(univ.Sequence):
  File "/usr/local/lib/python2.7/dist-packages/ndg_httpsclient-0.4.0-py2.7.egg/ndg/httpsclient/subj_alt_name.py", line 105, in AnotherName
    namedtype.NamedType('value', univ.Any().subtype(
AttributeError: 'module' object has no attribute 'Any'

**Comment by maglietti** [comment] 2015-06-17 20:24
Hi @tylerwei,

It looks to me as though your requests module is failing to initialize. I've tried multiple things on my machine and haven't been able to reproduce the error. 

Are you able to load the request module in the interactive Python shell?

```
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> 
```

I made sure to [upgrade](http://stackoverflow.com/questions/2720014/upgrading-all-packages-with-pip) all of the libraries on my machine via pip to make sure that there wasn't a compatibility issue. 

As a reference, I'm able to run the script without any problems on my MacBook.

```
$ python diagnostic_tools.py

Requesting locations that support the diagnostic-tools API.

There are 68 locations that can run dig in the Akamai Network
We will make our call from Kowloon, Hong Kong

Running dig from Kowloon, Hong Kong

<<--- snip --->>
```

Please make sure that your local copy of the repository is up to date with `git pull` and that your Python install is sane.

Michael

**Comment by maglietti** [comment] 2015-08-20 19:42
Closing this issue because Tyler didn't respond. Please reopen if you are having the same problem.

**Closed by maglietti** 2015-08-20 19:42 UTC
